// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/v11/pb/pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvOneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Val:
	//
	//	*KvOneof_Str
	//	*KvOneof_Bool
	//	*KvOneof_Bytes
	//	*KvOneof_Int64
	//	*KvOneof_Float64
	Val           isKvOneof_Val `protobuf_oneof:"val"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvOneof) Reset() {
	*x = KvOneof{}
	mi := &file_pkg_proto_v11_pb_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvOneof) ProtoMessage() {}

func (x *KvOneof) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v11_pb_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvOneof.ProtoReflect.Descriptor instead.
func (*KvOneof) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v11_pb_pb_proto_rawDescGZIP(), []int{0}
}

func (x *KvOneof) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvOneof) GetVal() isKvOneof_Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *KvOneof) GetStr() string {
	if x != nil {
		if x, ok := x.Val.(*KvOneof_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *KvOneof) GetBool() bool {
	if x != nil {
		if x, ok := x.Val.(*KvOneof_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *KvOneof) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Val.(*KvOneof_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *KvOneof) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Val.(*KvOneof_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *KvOneof) GetFloat64() float32 {
	if x != nil {
		if x, ok := x.Val.(*KvOneof_Float64); ok {
			return x.Float64
		}
	}
	return 0
}

type isKvOneof_Val interface {
	isKvOneof_Val()
}

type KvOneof_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type KvOneof_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type KvOneof_Bytes struct {
	Bytes []byte `protobuf:"bytes,4,opt,name=bytes,proto3,oneof"`
}

type KvOneof_Int64 struct {
	Int64 int64 `protobuf:"varint,5,opt,name=int64,proto3,oneof"`
}

type KvOneof_Float64 struct {
	Float64 float32 `protobuf:"fixed32,6,opt,name=float64,proto3,oneof"`
}

func (*KvOneof_Str) isKvOneof_Val() {}

func (*KvOneof_Bool) isKvOneof_Val() {}

func (*KvOneof_Bytes) isKvOneof_Val() {}

func (*KvOneof_Int64) isKvOneof_Val() {}

func (*KvOneof_Float64) isKvOneof_Val() {}

var File_pkg_proto_v11_pb_pb_proto protoreflect.FileDescriptor

const file_pkg_proto_v11_pb_pb_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/v11/pb/pb.proto\x12\tmgrpc.v11\"\x98\x01\n" +
	"\aKvOneof\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x03str\x18\x02 \x01(\tH\x00R\x03str\x12\x14\n" +
	"\x04bool\x18\x03 \x01(\bH\x00R\x04bool\x12\x16\n" +
	"\x05bytes\x18\x04 \x01(\fH\x00R\x05bytes\x12\x16\n" +
	"\x05int64\x18\x05 \x01(\x03H\x00R\x05int64\x12\x1a\n" +
	"\afloat64\x18\x06 \x01(\x02H\x00R\afloat64B\x05\n" +
	"\x03val26\n" +
	"\x03Rpc\x12/\n" +
	"\x05Oneof\x12\x12.mgrpc.v11.KvOneof\x1a\x12.mgrpc.v11.KvOneofB\x06Z\x04.;pbb\x06proto3"

var (
	file_pkg_proto_v11_pb_pb_proto_rawDescOnce sync.Once
	file_pkg_proto_v11_pb_pb_proto_rawDescData []byte
)

func file_pkg_proto_v11_pb_pb_proto_rawDescGZIP() []byte {
	file_pkg_proto_v11_pb_pb_proto_rawDescOnce.Do(func() {
		file_pkg_proto_v11_pb_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_v11_pb_pb_proto_rawDesc), len(file_pkg_proto_v11_pb_pb_proto_rawDesc)))
	})
	return file_pkg_proto_v11_pb_pb_proto_rawDescData
}

var file_pkg_proto_v11_pb_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_v11_pb_pb_proto_goTypes = []any{
	(*KvOneof)(nil), // 0: mgrpc.v11.KvOneof
}
var file_pkg_proto_v11_pb_pb_proto_depIdxs = []int32{
	0, // 0: mgrpc.v11.Rpc.Oneof:input_type -> mgrpc.v11.KvOneof
	0, // 1: mgrpc.v11.Rpc.Oneof:output_type -> mgrpc.v11.KvOneof
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_v11_pb_pb_proto_init() }
func file_pkg_proto_v11_pb_pb_proto_init() {
	if File_pkg_proto_v11_pb_pb_proto != nil {
		return
	}
	file_pkg_proto_v11_pb_pb_proto_msgTypes[0].OneofWrappers = []any{
		(*KvOneof_Str)(nil),
		(*KvOneof_Bool)(nil),
		(*KvOneof_Bytes)(nil),
		(*KvOneof_Int64)(nil),
		(*KvOneof_Float64)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_v11_pb_pb_proto_rawDesc), len(file_pkg_proto_v11_pb_pb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_v11_pb_pb_proto_goTypes,
		DependencyIndexes: file_pkg_proto_v11_pb_pb_proto_depIdxs,
		MessageInfos:      file_pkg_proto_v11_pb_pb_proto_msgTypes,
	}.Build()
	File_pkg_proto_v11_pb_pb_proto = out.File
	file_pkg_proto_v11_pb_pb_proto_goTypes = nil
	file_pkg_proto_v11_pb_pb_proto_depIdxs = nil
}
