// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/v10/pb/pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           bool                   `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvBool) Reset() {
	*x = KvBool{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvBool) ProtoMessage() {}

func (x *KvBool) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvBool.ProtoReflect.Descriptor instead.
func (*KvBool) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{0}
}

func (x *KvBool) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvBool) GetVal() bool {
	if x != nil {
		return x.Val
	}
	return false
}

type KvInt64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           int64                  `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvInt64) Reset() {
	*x = KvInt64{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvInt64) ProtoMessage() {}

func (x *KvInt64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvInt64.ProtoReflect.Descriptor instead.
func (*KvInt64) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{1}
}

func (x *KvInt64) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvInt64) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type KvUint64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           uint64                 `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvUint64) Reset() {
	*x = KvUint64{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvUint64) ProtoMessage() {}

func (x *KvUint64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvUint64.ProtoReflect.Descriptor instead.
func (*KvUint64) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{2}
}

func (x *KvUint64) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvUint64) GetVal() uint64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type KvFloat64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           float64                `protobuf:"fixed64,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvFloat64) Reset() {
	*x = KvFloat64{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvFloat64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvFloat64) ProtoMessage() {}

func (x *KvFloat64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvFloat64.ProtoReflect.Descriptor instead.
func (*KvFloat64) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{3}
}

func (x *KvFloat64) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvFloat64) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type KvString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvString) Reset() {
	*x = KvString{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvString) ProtoMessage() {}

func (x *KvString) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvString.ProtoReflect.Descriptor instead.
func (*KvString) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{4}
}

func (x *KvString) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvString) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type KvBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           []byte                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvBytes) Reset() {
	*x = KvBytes{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvBytes) ProtoMessage() {}

func (x *KvBytes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvBytes.ProtoReflect.Descriptor instead.
func (*KvBytes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{5}
}

func (x *KvBytes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvBytes) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type KvStringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           []string               `protobuf:"bytes,2,rep,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvStringArray) Reset() {
	*x = KvStringArray{}
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvStringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStringArray) ProtoMessage() {}

func (x *KvStringArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v10_pb_pb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStringArray.ProtoReflect.Descriptor instead.
func (*KvStringArray) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v10_pb_pb_proto_rawDescGZIP(), []int{6}
}

func (x *KvStringArray) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvStringArray) GetVal() []string {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_pkg_proto_v10_pb_pb_proto protoreflect.FileDescriptor

const file_pkg_proto_v10_pb_pb_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/v10/pb/pb.proto\x12\tmgrpc.v10\x1a\x19google/protobuf/any.proto\",\n" +
	"\x06KvBool\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\bR\x03val\"-\n" +
	"\aKvInt64\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x03R\x03val\".\n" +
	"\bKvUint64\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x04R\x03val\"/\n" +
	"\tKvFloat64\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x01R\x03val\".\n" +
	"\bKvString\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"-\n" +
	"\aKvBytes\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\fR\x03val\"3\n" +
	"\rKvStringArray\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x03(\tR\x03val2\xd3\n" +
	"\n" +
	"\x03Ask\x121\n" +
	"\x03Any\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\x127\n" +
	"\fInt64AskBool\x12\x12.mgrpc.v10.KvInt64\x1a\x11.mgrpc.v10.KvBool\"\x00\x129\n" +
	"\rInt64AskBytes\x12\x12.mgrpc.v10.KvInt64\x1a\x12.mgrpc.v10.KvBytes\"\x00\x129\n" +
	"\rInt64AskInt64\x12\x12.mgrpc.v10.KvInt64\x1a\x12.mgrpc.v10.KvInt64\"\x00\x12;\n" +
	"\x0eInt64AskUint64\x12\x12.mgrpc.v10.KvInt64\x1a\x13.mgrpc.v10.KvUint64\"\x00\x12=\n" +
	"\x0fInt64AskFloat64\x12\x12.mgrpc.v10.KvInt64\x1a\x14.mgrpc.v10.KvFloat64\"\x00\x12;\n" +
	"\x0eInt64AskString\x12\x12.mgrpc.v10.KvInt64\x1a\x13.mgrpc.v10.KvString\"\x00\x12E\n" +
	"\x13Int64AskStringArray\x12\x12.mgrpc.v10.KvInt64\x1a\x18.mgrpc.v10.KvStringArray\"\x00\x129\n" +
	"\rStringAskBool\x12\x13.mgrpc.v10.KvString\x1a\x11.mgrpc.v10.KvBool\"\x00\x12;\n" +
	"\x0eStringAskBytes\x12\x13.mgrpc.v10.KvString\x1a\x12.mgrpc.v10.KvBytes\"\x00\x12;\n" +
	"\x0eStringAskInt64\x12\x13.mgrpc.v10.KvString\x1a\x12.mgrpc.v10.KvInt64\"\x00\x12=\n" +
	"\x0fStringAskUint64\x12\x13.mgrpc.v10.KvString\x1a\x13.mgrpc.v10.KvUint64\"\x00\x12?\n" +
	"\x10StringAskFloat64\x12\x13.mgrpc.v10.KvString\x1a\x14.mgrpc.v10.KvFloat64\"\x00\x12=\n" +
	"\x0fStringAskString\x12\x13.mgrpc.v10.KvString\x1a\x13.mgrpc.v10.KvString\"\x00\x12G\n" +
	"\x14StringAskStringArray\x12\x13.mgrpc.v10.KvString\x1a\x18.mgrpc.v10.KvStringArray\"\x00\x127\n" +
	"\fBytesAskBool\x12\x12.mgrpc.v10.KvBytes\x1a\x11.mgrpc.v10.KvBool\"\x00\x129\n" +
	"\rBytesAskBytes\x12\x12.mgrpc.v10.KvBytes\x1a\x12.mgrpc.v10.KvBytes\"\x00\x129\n" +
	"\rBytesAskInt64\x12\x12.mgrpc.v10.KvBytes\x1a\x12.mgrpc.v10.KvInt64\"\x00\x12;\n" +
	"\x0eBytesAskUint64\x12\x12.mgrpc.v10.KvBytes\x1a\x13.mgrpc.v10.KvUint64\"\x00\x12=\n" +
	"\x0fBytesAskFloat64\x12\x12.mgrpc.v10.KvBytes\x1a\x14.mgrpc.v10.KvFloat64\"\x00\x12;\n" +
	"\x0eBytesAskString\x12\x12.mgrpc.v10.KvBytes\x1a\x13.mgrpc.v10.KvString\"\x00\x12E\n" +
	"\x13BytesAskStringArray\x12\x12.mgrpc.v10.KvBytes\x1a\x18.mgrpc.v10.KvStringArray\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_pkg_proto_v10_pb_pb_proto_rawDescOnce sync.Once
	file_pkg_proto_v10_pb_pb_proto_rawDescData []byte
)

func file_pkg_proto_v10_pb_pb_proto_rawDescGZIP() []byte {
	file_pkg_proto_v10_pb_pb_proto_rawDescOnce.Do(func() {
		file_pkg_proto_v10_pb_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_v10_pb_pb_proto_rawDesc), len(file_pkg_proto_v10_pb_pb_proto_rawDesc)))
	})
	return file_pkg_proto_v10_pb_pb_proto_rawDescData
}

var file_pkg_proto_v10_pb_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_v10_pb_pb_proto_goTypes = []any{
	(*KvBool)(nil),        // 0: mgrpc.v10.KvBool
	(*KvInt64)(nil),       // 1: mgrpc.v10.KvInt64
	(*KvUint64)(nil),      // 2: mgrpc.v10.KvUint64
	(*KvFloat64)(nil),     // 3: mgrpc.v10.KvFloat64
	(*KvString)(nil),      // 4: mgrpc.v10.KvString
	(*KvBytes)(nil),       // 5: mgrpc.v10.KvBytes
	(*KvStringArray)(nil), // 6: mgrpc.v10.KvStringArray
	(*anypb.Any)(nil),     // 7: google.protobuf.Any
}
var file_pkg_proto_v10_pb_pb_proto_depIdxs = []int32{
	7,  // 0: mgrpc.v10.Ask.Any:input_type -> google.protobuf.Any
	1,  // 1: mgrpc.v10.Ask.Int64AskBool:input_type -> mgrpc.v10.KvInt64
	1,  // 2: mgrpc.v10.Ask.Int64AskBytes:input_type -> mgrpc.v10.KvInt64
	1,  // 3: mgrpc.v10.Ask.Int64AskInt64:input_type -> mgrpc.v10.KvInt64
	1,  // 4: mgrpc.v10.Ask.Int64AskUint64:input_type -> mgrpc.v10.KvInt64
	1,  // 5: mgrpc.v10.Ask.Int64AskFloat64:input_type -> mgrpc.v10.KvInt64
	1,  // 6: mgrpc.v10.Ask.Int64AskString:input_type -> mgrpc.v10.KvInt64
	1,  // 7: mgrpc.v10.Ask.Int64AskStringArray:input_type -> mgrpc.v10.KvInt64
	4,  // 8: mgrpc.v10.Ask.StringAskBool:input_type -> mgrpc.v10.KvString
	4,  // 9: mgrpc.v10.Ask.StringAskBytes:input_type -> mgrpc.v10.KvString
	4,  // 10: mgrpc.v10.Ask.StringAskInt64:input_type -> mgrpc.v10.KvString
	4,  // 11: mgrpc.v10.Ask.StringAskUint64:input_type -> mgrpc.v10.KvString
	4,  // 12: mgrpc.v10.Ask.StringAskFloat64:input_type -> mgrpc.v10.KvString
	4,  // 13: mgrpc.v10.Ask.StringAskString:input_type -> mgrpc.v10.KvString
	4,  // 14: mgrpc.v10.Ask.StringAskStringArray:input_type -> mgrpc.v10.KvString
	5,  // 15: mgrpc.v10.Ask.BytesAskBool:input_type -> mgrpc.v10.KvBytes
	5,  // 16: mgrpc.v10.Ask.BytesAskBytes:input_type -> mgrpc.v10.KvBytes
	5,  // 17: mgrpc.v10.Ask.BytesAskInt64:input_type -> mgrpc.v10.KvBytes
	5,  // 18: mgrpc.v10.Ask.BytesAskUint64:input_type -> mgrpc.v10.KvBytes
	5,  // 19: mgrpc.v10.Ask.BytesAskFloat64:input_type -> mgrpc.v10.KvBytes
	5,  // 20: mgrpc.v10.Ask.BytesAskString:input_type -> mgrpc.v10.KvBytes
	5,  // 21: mgrpc.v10.Ask.BytesAskStringArray:input_type -> mgrpc.v10.KvBytes
	7,  // 22: mgrpc.v10.Ask.Any:output_type -> google.protobuf.Any
	0,  // 23: mgrpc.v10.Ask.Int64AskBool:output_type -> mgrpc.v10.KvBool
	5,  // 24: mgrpc.v10.Ask.Int64AskBytes:output_type -> mgrpc.v10.KvBytes
	1,  // 25: mgrpc.v10.Ask.Int64AskInt64:output_type -> mgrpc.v10.KvInt64
	2,  // 26: mgrpc.v10.Ask.Int64AskUint64:output_type -> mgrpc.v10.KvUint64
	3,  // 27: mgrpc.v10.Ask.Int64AskFloat64:output_type -> mgrpc.v10.KvFloat64
	4,  // 28: mgrpc.v10.Ask.Int64AskString:output_type -> mgrpc.v10.KvString
	6,  // 29: mgrpc.v10.Ask.Int64AskStringArray:output_type -> mgrpc.v10.KvStringArray
	0,  // 30: mgrpc.v10.Ask.StringAskBool:output_type -> mgrpc.v10.KvBool
	5,  // 31: mgrpc.v10.Ask.StringAskBytes:output_type -> mgrpc.v10.KvBytes
	1,  // 32: mgrpc.v10.Ask.StringAskInt64:output_type -> mgrpc.v10.KvInt64
	2,  // 33: mgrpc.v10.Ask.StringAskUint64:output_type -> mgrpc.v10.KvUint64
	3,  // 34: mgrpc.v10.Ask.StringAskFloat64:output_type -> mgrpc.v10.KvFloat64
	4,  // 35: mgrpc.v10.Ask.StringAskString:output_type -> mgrpc.v10.KvString
	6,  // 36: mgrpc.v10.Ask.StringAskStringArray:output_type -> mgrpc.v10.KvStringArray
	0,  // 37: mgrpc.v10.Ask.BytesAskBool:output_type -> mgrpc.v10.KvBool
	5,  // 38: mgrpc.v10.Ask.BytesAskBytes:output_type -> mgrpc.v10.KvBytes
	1,  // 39: mgrpc.v10.Ask.BytesAskInt64:output_type -> mgrpc.v10.KvInt64
	2,  // 40: mgrpc.v10.Ask.BytesAskUint64:output_type -> mgrpc.v10.KvUint64
	3,  // 41: mgrpc.v10.Ask.BytesAskFloat64:output_type -> mgrpc.v10.KvFloat64
	4,  // 42: mgrpc.v10.Ask.BytesAskString:output_type -> mgrpc.v10.KvString
	6,  // 43: mgrpc.v10.Ask.BytesAskStringArray:output_type -> mgrpc.v10.KvStringArray
	22, // [22:44] is the sub-list for method output_type
	0,  // [0:22] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_v10_pb_pb_proto_init() }
func file_pkg_proto_v10_pb_pb_proto_init() {
	if File_pkg_proto_v10_pb_pb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_v10_pb_pb_proto_rawDesc), len(file_pkg_proto_v10_pb_pb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_v10_pb_pb_proto_goTypes,
		DependencyIndexes: file_pkg_proto_v10_pb_pb_proto_depIdxs,
		MessageInfos:      file_pkg_proto_v10_pb_pb_proto_msgTypes,
	}.Build()
	File_pkg_proto_v10_pb_pb_proto = out.File
	file_pkg_proto_v10_pb_pb_proto_goTypes = nil
	file_pkg_proto_v10_pb_pb_proto_depIdxs = nil
}
