// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/proto/v10/pb/pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ask_Any_FullMethodName                  = "/mgrpc.v10.Ask/Any"
	Ask_Int64AskBool_FullMethodName         = "/mgrpc.v10.Ask/Int64AskBool"
	Ask_Int64AskBytes_FullMethodName        = "/mgrpc.v10.Ask/Int64AskBytes"
	Ask_Int64AskInt64_FullMethodName        = "/mgrpc.v10.Ask/Int64AskInt64"
	Ask_Int64AskUint64_FullMethodName       = "/mgrpc.v10.Ask/Int64AskUint64"
	Ask_Int64AskFloat64_FullMethodName      = "/mgrpc.v10.Ask/Int64AskFloat64"
	Ask_Int64AskString_FullMethodName       = "/mgrpc.v10.Ask/Int64AskString"
	Ask_Int64AskStringArray_FullMethodName  = "/mgrpc.v10.Ask/Int64AskStringArray"
	Ask_StringAskBool_FullMethodName        = "/mgrpc.v10.Ask/StringAskBool"
	Ask_StringAskBytes_FullMethodName       = "/mgrpc.v10.Ask/StringAskBytes"
	Ask_StringAskInt64_FullMethodName       = "/mgrpc.v10.Ask/StringAskInt64"
	Ask_StringAskUint64_FullMethodName      = "/mgrpc.v10.Ask/StringAskUint64"
	Ask_StringAskFloat64_FullMethodName     = "/mgrpc.v10.Ask/StringAskFloat64"
	Ask_StringAskString_FullMethodName      = "/mgrpc.v10.Ask/StringAskString"
	Ask_StringAskStringArray_FullMethodName = "/mgrpc.v10.Ask/StringAskStringArray"
	Ask_BytesAskBool_FullMethodName         = "/mgrpc.v10.Ask/BytesAskBool"
	Ask_BytesAskBytes_FullMethodName        = "/mgrpc.v10.Ask/BytesAskBytes"
	Ask_BytesAskInt64_FullMethodName        = "/mgrpc.v10.Ask/BytesAskInt64"
	Ask_BytesAskUint64_FullMethodName       = "/mgrpc.v10.Ask/BytesAskUint64"
	Ask_BytesAskFloat64_FullMethodName      = "/mgrpc.v10.Ask/BytesAskFloat64"
	Ask_BytesAskString_FullMethodName       = "/mgrpc.v10.Ask/BytesAskString"
	Ask_BytesAskStringArray_FullMethodName  = "/mgrpc.v10.Ask/BytesAskStringArray"
)

// AskClient is the client API for Ask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AskClient interface {
	Any(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*anypb.Any, error)
	Int64AskBool(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvBool, error)
	Int64AskBytes(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvBytes, error)
	Int64AskInt64(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvInt64, error)
	Int64AskUint64(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvUint64, error)
	Int64AskFloat64(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvFloat64, error)
	Int64AskString(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvString, error)
	Int64AskStringArray(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvStringArray, error)
	StringAskBool(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvBool, error)
	StringAskBytes(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvBytes, error)
	StringAskInt64(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvInt64, error)
	StringAskUint64(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvUint64, error)
	StringAskFloat64(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvFloat64, error)
	StringAskString(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvString, error)
	StringAskStringArray(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvStringArray, error)
	BytesAskBool(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvBool, error)
	BytesAskBytes(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvBytes, error)
	BytesAskInt64(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvInt64, error)
	BytesAskUint64(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvUint64, error)
	BytesAskFloat64(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvFloat64, error)
	BytesAskString(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvString, error)
	BytesAskStringArray(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvStringArray, error)
}

type askClient struct {
	cc grpc.ClientConnInterface
}

func NewAskClient(cc grpc.ClientConnInterface) AskClient {
	return &askClient{cc}
}

func (c *askClient) Any(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*anypb.Any, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(anypb.Any)
	err := c.cc.Invoke(ctx, Ask_Any_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskBool(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBool)
	err := c.cc.Invoke(ctx, Ask_Int64AskBool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskBytes(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvBytes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBytes)
	err := c.cc.Invoke(ctx, Ask_Int64AskBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskInt64(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvInt64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvInt64)
	err := c.cc.Invoke(ctx, Ask_Int64AskInt64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskUint64(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvUint64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvUint64)
	err := c.cc.Invoke(ctx, Ask_Int64AskUint64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskFloat64(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvFloat64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvFloat64)
	err := c.cc.Invoke(ctx, Ask_Int64AskFloat64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskString(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvString, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvString)
	err := c.cc.Invoke(ctx, Ask_Int64AskString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) Int64AskStringArray(ctx context.Context, in *KvInt64, opts ...grpc.CallOption) (*KvStringArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvStringArray)
	err := c.cc.Invoke(ctx, Ask_Int64AskStringArray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskBool(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBool)
	err := c.cc.Invoke(ctx, Ask_StringAskBool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskBytes(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvBytes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBytes)
	err := c.cc.Invoke(ctx, Ask_StringAskBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskInt64(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvInt64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvInt64)
	err := c.cc.Invoke(ctx, Ask_StringAskInt64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskUint64(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvUint64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvUint64)
	err := c.cc.Invoke(ctx, Ask_StringAskUint64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskFloat64(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvFloat64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvFloat64)
	err := c.cc.Invoke(ctx, Ask_StringAskFloat64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskString(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvString, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvString)
	err := c.cc.Invoke(ctx, Ask_StringAskString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) StringAskStringArray(ctx context.Context, in *KvString, opts ...grpc.CallOption) (*KvStringArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvStringArray)
	err := c.cc.Invoke(ctx, Ask_StringAskStringArray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskBool(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBool)
	err := c.cc.Invoke(ctx, Ask_BytesAskBool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskBytes(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvBytes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBytes)
	err := c.cc.Invoke(ctx, Ask_BytesAskBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskInt64(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvInt64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvInt64)
	err := c.cc.Invoke(ctx, Ask_BytesAskInt64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskUint64(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvUint64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvUint64)
	err := c.cc.Invoke(ctx, Ask_BytesAskUint64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskFloat64(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvFloat64, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvFloat64)
	err := c.cc.Invoke(ctx, Ask_BytesAskFloat64_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskString(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvString, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvString)
	err := c.cc.Invoke(ctx, Ask_BytesAskString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *askClient) BytesAskStringArray(ctx context.Context, in *KvBytes, opts ...grpc.CallOption) (*KvStringArray, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvStringArray)
	err := c.cc.Invoke(ctx, Ask_BytesAskStringArray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AskServer is the server API for Ask service.
// All implementations must embed UnimplementedAskServer
// for forward compatibility.
type AskServer interface {
	Any(context.Context, *anypb.Any) (*anypb.Any, error)
	Int64AskBool(context.Context, *KvInt64) (*KvBool, error)
	Int64AskBytes(context.Context, *KvInt64) (*KvBytes, error)
	Int64AskInt64(context.Context, *KvInt64) (*KvInt64, error)
	Int64AskUint64(context.Context, *KvInt64) (*KvUint64, error)
	Int64AskFloat64(context.Context, *KvInt64) (*KvFloat64, error)
	Int64AskString(context.Context, *KvInt64) (*KvString, error)
	Int64AskStringArray(context.Context, *KvInt64) (*KvStringArray, error)
	StringAskBool(context.Context, *KvString) (*KvBool, error)
	StringAskBytes(context.Context, *KvString) (*KvBytes, error)
	StringAskInt64(context.Context, *KvString) (*KvInt64, error)
	StringAskUint64(context.Context, *KvString) (*KvUint64, error)
	StringAskFloat64(context.Context, *KvString) (*KvFloat64, error)
	StringAskString(context.Context, *KvString) (*KvString, error)
	StringAskStringArray(context.Context, *KvString) (*KvStringArray, error)
	BytesAskBool(context.Context, *KvBytes) (*KvBool, error)
	BytesAskBytes(context.Context, *KvBytes) (*KvBytes, error)
	BytesAskInt64(context.Context, *KvBytes) (*KvInt64, error)
	BytesAskUint64(context.Context, *KvBytes) (*KvUint64, error)
	BytesAskFloat64(context.Context, *KvBytes) (*KvFloat64, error)
	BytesAskString(context.Context, *KvBytes) (*KvString, error)
	BytesAskStringArray(context.Context, *KvBytes) (*KvStringArray, error)
	mustEmbedUnimplementedAskServer()
}

// UnimplementedAskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAskServer struct{}

func (UnimplementedAskServer) Any(context.Context, *anypb.Any) (*anypb.Any, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Any not implemented")
}
func (UnimplementedAskServer) Int64AskBool(context.Context, *KvInt64) (*KvBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskBool not implemented")
}
func (UnimplementedAskServer) Int64AskBytes(context.Context, *KvInt64) (*KvBytes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskBytes not implemented")
}
func (UnimplementedAskServer) Int64AskInt64(context.Context, *KvInt64) (*KvInt64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskInt64 not implemented")
}
func (UnimplementedAskServer) Int64AskUint64(context.Context, *KvInt64) (*KvUint64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskUint64 not implemented")
}
func (UnimplementedAskServer) Int64AskFloat64(context.Context, *KvInt64) (*KvFloat64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskFloat64 not implemented")
}
func (UnimplementedAskServer) Int64AskString(context.Context, *KvInt64) (*KvString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskString not implemented")
}
func (UnimplementedAskServer) Int64AskStringArray(context.Context, *KvInt64) (*KvStringArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Int64AskStringArray not implemented")
}
func (UnimplementedAskServer) StringAskBool(context.Context, *KvString) (*KvBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskBool not implemented")
}
func (UnimplementedAskServer) StringAskBytes(context.Context, *KvString) (*KvBytes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskBytes not implemented")
}
func (UnimplementedAskServer) StringAskInt64(context.Context, *KvString) (*KvInt64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskInt64 not implemented")
}
func (UnimplementedAskServer) StringAskUint64(context.Context, *KvString) (*KvUint64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskUint64 not implemented")
}
func (UnimplementedAskServer) StringAskFloat64(context.Context, *KvString) (*KvFloat64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskFloat64 not implemented")
}
func (UnimplementedAskServer) StringAskString(context.Context, *KvString) (*KvString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskString not implemented")
}
func (UnimplementedAskServer) StringAskStringArray(context.Context, *KvString) (*KvStringArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringAskStringArray not implemented")
}
func (UnimplementedAskServer) BytesAskBool(context.Context, *KvBytes) (*KvBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskBool not implemented")
}
func (UnimplementedAskServer) BytesAskBytes(context.Context, *KvBytes) (*KvBytes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskBytes not implemented")
}
func (UnimplementedAskServer) BytesAskInt64(context.Context, *KvBytes) (*KvInt64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskInt64 not implemented")
}
func (UnimplementedAskServer) BytesAskUint64(context.Context, *KvBytes) (*KvUint64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskUint64 not implemented")
}
func (UnimplementedAskServer) BytesAskFloat64(context.Context, *KvBytes) (*KvFloat64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskFloat64 not implemented")
}
func (UnimplementedAskServer) BytesAskString(context.Context, *KvBytes) (*KvString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskString not implemented")
}
func (UnimplementedAskServer) BytesAskStringArray(context.Context, *KvBytes) (*KvStringArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesAskStringArray not implemented")
}
func (UnimplementedAskServer) mustEmbedUnimplementedAskServer() {}
func (UnimplementedAskServer) testEmbeddedByValue()             {}

// UnsafeAskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AskServer will
// result in compilation errors.
type UnsafeAskServer interface {
	mustEmbedUnimplementedAskServer()
}

func RegisterAskServer(s grpc.ServiceRegistrar, srv AskServer) {
	// If the following call pancis, it indicates UnimplementedAskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ask_ServiceDesc, srv)
}

func _Ask_Any_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(anypb.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Any(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Any_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Any(ctx, req.(*anypb.Any))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskBool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskBool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskBool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskBool(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskBytes(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskInt64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskInt64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskInt64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskInt64(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskUint64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskUint64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskUint64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskUint64(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskFloat64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskFloat64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskFloat64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskFloat64(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskString(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_Int64AskStringArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvInt64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).Int64AskStringArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_Int64AskStringArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).Int64AskStringArray(ctx, req.(*KvInt64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskBool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskBool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskBool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskBool(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskBytes(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskInt64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskInt64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskInt64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskInt64(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskUint64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskUint64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskUint64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskUint64(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskFloat64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskFloat64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskFloat64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskFloat64(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskString(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_StringAskStringArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).StringAskStringArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_StringAskStringArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).StringAskStringArray(ctx, req.(*KvString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskBool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskBool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskBool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskBool(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskBytes(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskInt64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskInt64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskInt64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskInt64(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskUint64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskUint64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskUint64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskUint64(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskFloat64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskFloat64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskFloat64_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskFloat64(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskString(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ask_BytesAskStringArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServer).BytesAskStringArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ask_BytesAskStringArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServer).BytesAskStringArray(ctx, req.(*KvBytes))
	}
	return interceptor(ctx, in, info, handler)
}

// Ask_ServiceDesc is the grpc.ServiceDesc for Ask service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ask_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mgrpc.v10.Ask",
	HandlerType: (*AskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Any",
			Handler:    _Ask_Any_Handler,
		},
		{
			MethodName: "Int64AskBool",
			Handler:    _Ask_Int64AskBool_Handler,
		},
		{
			MethodName: "Int64AskBytes",
			Handler:    _Ask_Int64AskBytes_Handler,
		},
		{
			MethodName: "Int64AskInt64",
			Handler:    _Ask_Int64AskInt64_Handler,
		},
		{
			MethodName: "Int64AskUint64",
			Handler:    _Ask_Int64AskUint64_Handler,
		},
		{
			MethodName: "Int64AskFloat64",
			Handler:    _Ask_Int64AskFloat64_Handler,
		},
		{
			MethodName: "Int64AskString",
			Handler:    _Ask_Int64AskString_Handler,
		},
		{
			MethodName: "Int64AskStringArray",
			Handler:    _Ask_Int64AskStringArray_Handler,
		},
		{
			MethodName: "StringAskBool",
			Handler:    _Ask_StringAskBool_Handler,
		},
		{
			MethodName: "StringAskBytes",
			Handler:    _Ask_StringAskBytes_Handler,
		},
		{
			MethodName: "StringAskInt64",
			Handler:    _Ask_StringAskInt64_Handler,
		},
		{
			MethodName: "StringAskUint64",
			Handler:    _Ask_StringAskUint64_Handler,
		},
		{
			MethodName: "StringAskFloat64",
			Handler:    _Ask_StringAskFloat64_Handler,
		},
		{
			MethodName: "StringAskString",
			Handler:    _Ask_StringAskString_Handler,
		},
		{
			MethodName: "StringAskStringArray",
			Handler:    _Ask_StringAskStringArray_Handler,
		},
		{
			MethodName: "BytesAskBool",
			Handler:    _Ask_BytesAskBool_Handler,
		},
		{
			MethodName: "BytesAskBytes",
			Handler:    _Ask_BytesAskBytes_Handler,
		},
		{
			MethodName: "BytesAskInt64",
			Handler:    _Ask_BytesAskInt64_Handler,
		},
		{
			MethodName: "BytesAskUint64",
			Handler:    _Ask_BytesAskUint64_Handler,
		},
		{
			MethodName: "BytesAskFloat64",
			Handler:    _Ask_BytesAskFloat64_Handler,
		},
		{
			MethodName: "BytesAskString",
			Handler:    _Ask_BytesAskString_Handler,
		},
		{
			MethodName: "BytesAskStringArray",
			Handler:    _Ask_BytesAskStringArray_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/v10/pb/pb.proto",
}
